export const useStyles = (theme) => ({
  projectDetailsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    "& h5": {
      margin: 0,
      color: theme.palette.text.darkShadedGray,
      fontSize: 16,
      fontWeight: 700,
      lineHeight: "22px",
    },
  },
  projectDetailsValue: {
    width: "100%",
    textAlign: "left",
    position: "relative",
    height: "1rem",
    "& span": {
      width: "100%",
      overflow: "hidden",
      textOverflow: "ellipsis",
      display: "-webkit-box",
      height: "min-content",
      "-webkit-line-clamp": 1,
      "-webkit-box-orient": "vertical",
      transition: "all 0.1s",
      overflowWrap: "break-word",
    },
    "& span:hover": {
      height: "min-content",
      background: "white",
      paddingBottom: 5,
      "-webkit-line-clamp": 10,
      borderRadius: 5,
      transition: "all 0.1s",
    },
  },
  projectURLContainer: {
    "& > div": {
      display: "flex",
      alignItems: "center",
    },
    "& svg": {
      marginRight: 5,
      color: theme.palette.text.primary,
    },
    "& a": {
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
      display: "block",
      color: theme.palette.text.primary,
      fontWeight: 400,
      letterSpacing: 0.25,
      wordBreak: "break-all",
      textDecoration: "none",
      "&:hover": { textDecoration: "underline" },
    },
  },
});
