export const useStyles = theme => ({
  hamburger: {
    padding: 10,
    margin: "0 39px 0 23px",
    display: "none",
    cursor: "pointer",
    "& svg": {
      color: theme.palette.text.white,
    },
    "@media (max-width:768px)": { display: "block" },
  },
  mobileNavContainer: {
    display: "flex",
    alignItems: "center",
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 1,
    backgroundColor: theme.palette.text.purple,
    "@media (min-width:1024px)": { display: "none" },
  },
  closeMenuIcon: {
    color: theme.palette.text.white,
    position: "absolute",
    top: 30,
    left: 40,
    cursor: "pointer",
    zIndex: 999,
  },
  mobileNavigation: {
    boxSizing: "border-box",
    width: "100%",
    height: "100%",
    padding: "90px 0 50px",
    overflow: "auto",
    textAlign: "left",
    "& a": {
      paddingBottom: 25,
      borderBottom: "none",
      display: "inline-block",
      color: theme.palette.text.white,
      fontSize: 24,
      lineHeight: "33px",
      textAlign: "center",
      textDecoration: "none",
    },
    "@media(min-width: 1024px)": { display: "none" },
  },
});
