import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles((theme) => ({
  card: {
    minHeight: 440,
    width: 302,
    paddingTop: 10,
    display: "inline-block",
    position: "relative",
    fontFamily: theme.typography.primary.main,
    fontSize: 18,
    "&:hover": {
      backgroundColor: theme.palette.text.offWhiteColor,
      "& h4": { color: theme.palette.text.primary },
      "& .MuiCardActions-spacing": { backgroundColor: theme.palette.text.offWhiteColor },
    },
  },
  cardHeader: {
    display: "flex",
    gap: 10,
    padding: "0 18px",
    alignItems: "flex-start",
    "& .MuiCardHeader-avatar": { marginRight: 0 },
    "& .MuiCardHeader-content": {
      textAlign: "left",
    },
  },
  cardHeaderContent: {
    width: "100%",
    textAlign: "left",
    position: "relative",
    "& span": {
      paddingLeft: 5,
      overflow: "hidden",
      textOverflow: "ellipsis",
      display: "-webkit-box",
      height: "min-content",
      "-webkit-line-clamp": 1,
      "-webkit-box-orient": "vertical",
      transition: "all 0.1s",
    },
    "& span:hover": {
      position: "absolute",
      overflow: "auto",
      height: "min-content",
      background: "rgb(250, 250, 250)",
      "-webkit-line-clamp": 10,
      padding: "0 0 5px 5px",
      borderRadius: 5,
      transition: "all 0.1s",
    },
  },
  cardTitle: {
    fontFamily: theme.typography.primary.main,
    fontSize: 18,
    fontWeight: 600,
    color: theme.palette.text.darkShadedGray,
    letterSpacing: 0.23,
    lineHeight: "23px",
    height: "1.5rem",
  },
  cardSubheader: {
    margin: 0,
    fontFamily: theme.typography.primary.main,
    fontSize: 10,
    color: theme.palette.text.lightShadedGray,
    fontWeight: 600,
    letterSpacing: 1.67,
    lineHeight: "16px",
    textTransform: "uppercase",
    height: "1rem",
  },
  CardMedia: {
    height: 175,
    margin: "12px 0 17px",
  },
  cardContent: {
    padding: "0 18px",
    fontFamily: theme.typography.primary.main,
    fontSize: 18,
    textAlign: "left",
  },
  cardTypograpy: {
    marginTop: 8,
    color: theme.palette.text.mediumShadeGray,
    fontFamily: theme.typography.primary.main,
    fontSize: 14,
    letterSpacing: 0.25,
    lineHeight: "21px",
  },
  cardActions: {
    boxSizing: "border-box",
    width: "100%",
    position: "absolute",
    bottom: 20,
    padding: "0 11px",
    justifyContent: "space-between",
    backgroundColor: theme.palette.text.white,
    "& button": { padding: 0 },
  },
  ratingStars: {
    "& label": { fontSize: 24 },
    "& .dv-star-rating-empty-star i": { color: theme.palette.text.disabledBtnBg },
  },
}));
