export const useStyles = (theme) => ({
  mainContainer: {
    gap: 24,
    display: "flex",
    flexDirection: "column",
    "& p": {
      margin: 0,
    },
  },
  description: {
    margin: 0,
    textAlign: "center",
    color: theme.palette.text.alertBoxColor,
    fontFamily: theme.typography.primary.main,
  },
  paymentInfoCard: {
    display: "flex",
    justifyContent: "space-between",
  },
  buttonContainer: {
    marginTop: 35,
    textAlign: "center",
    justifyContent: "center",
    "& div": {
      display: "inline-block",
    },
  },
  channelSelectionTitle: {
    marginBottom: 5,
    display: "inline-block",
    color: theme.palette.text.mediumShadeGray,
    fontSize: 16,
    fontWeight: 600,
  },
  metamaskButtonContainer: {
    width: "100%",
    textAlign: "right",
  },
  tooltip: { fontSize: 14 },
  paymentChannelAndDetails: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 24,
    "@media(max-width:767px)": { flexDirection: "column" },
  },
  paymentChannelDropDownContainer: {
    "& fieldset": { display: "none" },
  },
  infoIconContainer: {
    marginRight: 10,
    alignSelf: "center",
    color: theme.palette.text.lightShadedGray,
    fontSize: 18,
  },
  paymentChannelDropDown: {
    width: 278,
    padding: "0 10px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(25,25,25,0.32)",
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    position: "relative",
    "& .MuiFormControl-root": { width: "90%" },
    "& .MuiSelect-outlined": { padding: "15px 14px" },
    "& .MuiSelect-icon": { color: theme.palette.text.darkShadedGray },
    "@media(min-width: 768px) and (max-width: 960px)": { width: 178 },
  },
  dropDownTitle: {
    padding: "0 5px",
    position: "absolute",
    top: -11,
    left: 10,
    backgroundColor: theme.palette.text.white,
    color: theme.palette.text.dialogTitle,
    fontSize: 12,
    letterSpacing: 0.4,
  },
  walletIcon: { color: theme.palette.text.lightShadedGray },
  btnsContainer: {
    marginTop: 64,
    textAlign: "center",
    "& button": { marginRight: "32px" },
  },
});
