export const useStyles = theme => ({
  DownloadTokenBtn: {
    display: "block",
    color: "white",
    marginLeft: 32,
    backgroundColor: theme.palette.text.primary,
    marginBottom: 10,
  },
  installAndRunContainer: {
    paddingTop: 11,
    marginBottom: 25,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: theme.palette.text.verticalTabLeftBorder,
    "& h3": {
      padding: "12px 22px",
      borderBottomWidth: 1,
      borderBottomStyle: "solid",
      borderBottomColor: theme.palette.text.gray1,
      margin: 0,
      color: theme.palette.text.darkShadedGray,
      fontSize: 20,
      fontWeight: 400,
    },
    "& .ProjectDetails-projectDetailsContainer-415": {
      "& h3": { marginBottom: 20 },
    },
  },
  infoIcon: {
    paddingRight: 12,
    paddingTop: 20,
    color: theme.palette.text.lightGray,
    fontSize: 20,
    verticalAlign: "sub",
  },
  overViewContainer: {
    boxShadow: "0 1px 1px 0 rgba(0,0,0,0.07), 0 2px 1px -1px rgba(0,0,0,0.07), 0 1px 3px 0 rgba(0,0,0,0.1)",
    backgroundColor: theme.palette.text.white,
    borderRadius: 4,
    paddingBottom: 20,
    paddingLeft: 20,
    "& p": {
      margin: 0,
      fontSize: 14,
      color: theme.palette.text.mediumShadeGray,
      letterSpacing: "0.25px",
      lineHeight: "20px",
    },
    "& h4": {
      margin: "30px 0 0",
      color: theme.palette.text.darkShadedGray,
      fontSize: 20,
      fontWeight: 400,
    },
    "& ul": {
      margin: "20px 0 0",
      padding: "0 22px",
      display: "flex",
      "& div": {
        "&:last-of-type": { marginLeft: "26%" },
      },
      "& li": {
        display: "flex",
        color: theme.palette.text.mediumShadeGray,
        fontSize: 14,
        lineHeight: "24px",
        letterSpacing: "0.25px",
        listStyle: "none",
      },
    },
    "& h5": {
      margin: "40px 45px 0 0",
      display: "inline-block",
      color: theme.palette.text.lightShadedGray,
      fontSize: 16,
      "@media(max-width:800px)": { paddingLeft: 0 },
    },
  },
  integrationSetupContainer: {
    paddingBottom: 25,
    margin: "0 25px 0 0",
    borderRadius: 4,
    boxShadow: "0 1px 1px 0 rgba(0,0,0,0.07), 0 2px 1px -1px rgba(0,0,0,0.07), 0 1px 3px 0 rgba(0,0,0,0.1)",
    backgroundColor: theme.palette.text.white,
  },
  integrationContent: {
    minHeight: 500,
    padding: "0 22px",
    paddingBottom: 10,
  },
  tabsHeader: {
    backgroundColor: "transparent",
    color: theme.palette.text.lightShadedGray,
    boxShadow: "none",
    "& button": {
      minWidth: "auto",
      padding: 0,
      marginRight: 40,
      fontSize: 18,
      textTransform: "none",
      color: theme.palette.text.lightShadedGray,
      fontFamily: "sans-serif",
    },
    "& .Mui-selected": { color: theme.palette.text.primary },
    "& .MuiTabs-indicator": { backgroundColor: theme.palette.text.primary },
  },
});
